[package]
name = "rustillium"
version = "0.2.0"
edition = "2024"

[dependencies]
gpgme = "0.11"
toml = "0.9.2"
config = "0.15.13"
wgpu = "25"
eframe = { version = "0.32.0", features = ["wgpu"] }
git2 = "0.20.2"

[dependencies.totp-rs]
version = "^5.0"
features = ["otpauth"]
